import Head from "next/head";
import { wrapper } from "@/redux/store";
import { getUsers } from "@/redux/resucers/userReducer";
import axios from "axios";
import { useSelector } from "react-redux";
import Link from "next/link";

export default function Home() {
  const { users } = useSelector((state) => state.users);

  return (
    <>
      <Head>
        <title>
          {users && users.length > 0 ? users[0].name : "Demo - app"}{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="users">
        {users &&
          users.length > 0 &&
          users.map((item) => (
            <Link href={"/details/"+item.id} key={item.id}>
              <h3>{item.name}</h3>
            </Link> 
          ))}
      </div>
    </>
  );
}
export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    const response = await axios.get(
      "https://jsonplaceholder.typicode.com/users"
    );
    store.dispatch(getUsers(response.data));
  }
);
